import { useState } from 'react';
import { ArrowRight, MapPin, Search, ShoppingCart, Heart, Star, Leaf, Send, Filter, CheckCircle2 } from 'lucide-react';
import { MARKETS, PRODUCTS, FARMERS } from '../data/data'; import Img from './Img'; import { navigate } from '../router';
function Header({title,sub}){return <div className="inner-page-head wrap"><span className="eyebrow">MarketLink</span><h1>{title}</h1><p>{sub}</p></div>}
export function MarketsPage(){return <><Header title="Explore Farmers Markets" sub="Find fresh local produce, market days and convenient pickup points."/><div className="wrap catalog-grid">{MARKETS.map(m=><article className="catalog-card" key={m.name}><div className="catalog-img"><Img src={m.img} alt={m.name}/><span>{m.type}</span></div><div className="catalog-body"><h3>{m.name}</h3><p><MapPin size={14}/> {m.city} • {m.km} km</p><small>{m.farmers} local farmers • ★ {m.rating}</small><button className="btn sm" onClick={()=>navigate('/markets/'+m.name.toLowerCase().replaceAll(' ','-'))}>View Market <ArrowRight size={14}/></button></div></article>)}</div></>}
export function ProductsPage(){const [q,setQ]=useState(''); const list=PRODUCTS.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())); return <><Header title="Fresh Products" sub="Browse vegetables, fruits and seasonal produce from local farmers."/><div className="wrap product-toolbar"><div><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/></div><button className="btn ghost"><Filter size={15}/> Filters</button></div><div className="wrap catalog-grid product-catalog">{list.map(p=><article className="product-card" key={p.name}><div className="pc-img"><Img src={p.img} alt={p.name}/><button><Heart size={17}/></button><span>{p.badge}</span></div><div className="pc-body"><h3>{p.name}</h3><p>{p.farmer} • {p.km} km</p><strong>Rs. {p.price}<small>/{p.unit}</small></strong><button className="btn full" onClick={()=>navigate('/cart')}>Add to Cart <ShoppingCart size={15}/></button></div></article>)}</div></>}
export function FarmersPage(){return <><Header title="Meet Local Farmers" sub="Real people growing and supplying fresh food to their communities."/><div className="wrap catalog-grid farmer-catalog">{FARMERS.map(f=><article className="farmer-card" key={f.name}><div><Img src={f.img} alt={f.name}/></div><section><span className="eyebrow">{f.badge}</span><h3>{f.name}</h3><p>{f.role}</p><small><MapPin size={13}/> Lahore • {f.km} km</small><div>{f.tags.map(t=><em key={t}>{t}</em>)}</div><button className="btn sm" onClick={()=>navigate('/register')}>Connect with Farmer <ArrowRight size={14}/></button></section></article>)}</div></>}
export function AboutPage(){return <><Header title="About MarketLink" sub="A digital bridge between local farmers, markets and their communities."/><div className="wrap info-page"><img src="https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1300&q=85" alt="Farm landscape"/><div><span className="eyebrow">Our purpose</span><h2>Fresh food. Stronger local connections.</h2><p>MarketLink brings market availability, farmer profiles, product discovery and pickup pre-orders into one friendly experience. Customers can discover nearby markets, browse products, save favorites and review completed orders.</p><button className="btn" onClick={()=>navigate('/markets')}>Explore Markets <ArrowRight size={15}/></button></div></div></>}
export function ContactPage(){return <><Header title="Contact Us" sub="Have a question about markets, farmers or pickup? Reach out."/><div className="wrap contact-grid"><form className="contact-form" onSubmit={e=>{e.preventDefault();alert('Message sent in frontend demo.')}}><label>Name<input required placeholder="Your name"/></label><label>Email<input type="email" required placeholder="you@example.com"/></label><label>Message<textarea required placeholder="How can we help?"/></label><button className="btn" type="submit">Send Message <Send size={15}/></button></form><div className="contact-card"><MapPin size={25}/><h3>MarketLink Community Hub</h3><p>Lahore, Pakistan</p><small>Map integration can be connected to Google Maps or OpenStreetMap in the backend phase.</small><button className="btn ghost" onClick={()=>navigate('/markets')}>Find Markets <MapPin size={15}/></button></div></div></>}
export function CartPage(){return <><Header title="Your Basket" sub="Review your selected produce before choosing a pickup slot."/><div className="wrap cart-page"><div className="cart-item"><div><CheckCircle2 size={22}/><div><b>Fresh Tomatoes</b><small>1 kg • Ali Raza</small></div></div><strong>Rs. 120</strong></div><div className="cart-total"><span>Total at pickup</span><b>Rs. 120</b><button className="btn" onClick={()=>navigate('/dashboard/customer/orders')}>Continue to Pickup <ArrowRight size={15}/></button></div></div></>}
